approvals:
  pattern: "^(:\\+1:|👍|\\+1|:thumbsup:|[Ll][Gg][Tt][Mm])$"
  minimum: 1
  ignore: pr_opener
  from:
    orgs:
      - zalando
    collaborators: true
X-Zalando-Team: zcpe
X-Zalando-Type: code
